# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5TdI-UCVM8ZYLicjKVVRRe_POnqOsEn
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,7])
y=np.array([0,150])

plt.plot(x,y)
plt.show

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,3,5,7])
y=np.array([0,70,20,150])

plt.plot(x,y)
plt.show

import matplotlib.pyplot as plt
import numpy as np


y=np.array([0,70,20,150])

plt.plot(y, 'o:r')
plt.show

import matplotlib.pyplot as plt
import numpy as np


y=np.array([0,100,20,150])

plt.plot(y, marker='o')
plt.show

import matplotlib.pyplot as plt
import numpy as np


y=np.array([5,30,20,50])

plt.plot(y, marker='o', ms=25)
plt.show

import matplotlib.pyplot as plt
import numpy as np


y=np.array([5,30,20,50])

plt.plot(y, marker='o', ms=25, mec='black')
plt.show

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([5,30,20,50])
y1=np.array([9,25,40,70])
x2=np.array([1,14,23,36])
y2=np.array([4,77,85,63])

plt.plot(x1,y1,x2,y2)
plt.show

import matplotlib.pyplot as plt
import numpy as np


y=np.array([5,30,20,50])

plt.plot(y, marker='o', ms=25, mfc='black')
plt.show

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,3,5,7,9])
y=np.array([0,70,20,150,25])

plt.scatter(x,y)
plt.show

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,3,5,7,9])
y=np.array([0,70,20,150,25])
plt.scatter(x,y,color='green')

x=np.array([1,5,4,6,9])
y=np.array([10,20,55,35,80])
plt.scatter(x,y,color='black')

plt.show

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,5,4,6,9])
y=np.array([10,20,55,35,80])
mycolor=['red','green','lime','yellow','aqua']
size=[10,20,30,12,15]
plt.scatter(x,y,color=mycolor,s=size)

plt.show